use cached openssl

diff --git a/.github/workflows/build-ton-linux-x86-64-shared.yml b/.github/workflows/build-ton-linux-x86-64-shared.yml
--- a/.github/workflows/build-ton-linux-x86-64-shared.yml
+++ b/.github/workflows/build-ton-linux-x86-64-shared.yml
@@ -27,13 +27,52 @@ jobs:
         chmod +x llvm.sh
         sudo ./llvm.sh 16 all
 
+    - name: Cache OpenSSL
+      id: cache-openssl
+      uses: actions/cache@v4
+      with:
+        path: openssl_3
+        key: ${{ runner.os }}-openssl_3
+
+    - name: Clone and compile OpenSSL 3.1.4
+      if: steps.cache-openssl_3.outputs.cache-hit != 'true'
+      run: |
+        git clone https://github.com/openssl/openssl openssl_3
+        cd openssl_3
+        opensslPath=`pwd`
+        git checkout openssl-3.1.4
+        ./config
+        make build_libs -j12
+
     - name: Build TON
       run: |
         git submodule sync --recursive
         git submodule update
-        cp assembly/native/build-ubuntu-shared.sh .
-        chmod +x build-ubuntu-shared.sh
-        ./build-ubuntu-shared.sh -t -a
+        opensslPath=`pwd`/openssl_3
+        mkdir build
+        cd build
+        cmake -GNinja -DTON_USE_JEMALLOC=ON .. \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DOPENSSL_ROOT_DIR$opensslPath \
+        -DOPENSSL_INCLUDE_DIR=$opensslPath/include \
+        -DOPENSSL_CRYPTO_LIBRARY=$opensslPath/libcrypto.so
+
+    - name: Output artifacts
+      run: |
+        rm -rf artifacts
+        mkdir artifacts
+        mv build/tonlib/libtonlibjson.so.0.5 build/tonlib/libtonlibjson.so
+        cp build/storage/storage-daemon/storage-daemon build/storage/storage-daemon/storage-daemon-cli \
+        build/crypto/fift build/crypto/tlbc build/crypto/func build/tolk/tolk build/crypto/create-state build/blockchain-explorer/blockchain-explorer \
+        build/validator-engine-console/validator-engine-console build/tonlib/tonlib-cli build/utils/proxy-liteserver \
+        build/tonlib/libtonlibjson.so build/http/http-proxy build/rldp-http-proxy/rldp-http-proxy \
+        build/dht-server/dht-server build/lite-client/lite-client build/validator-engine/validator-engine \
+        build/utils/generate-random-id build/utils/json2tlo build/adnl/adnl-proxy build/emulator/libemulator.so \
+        artifacts
+        test $? -eq 0 || { echo "Can't copy final binaries"; exit 1; }
+        cp -R crypto/smartcont artifacts
+        cp -R crypto/fift/lib artifacts
+        chmod -R +x artifacts/*
 
     - name: Upload artifacts
       uses: actions/upload-artifact@master
